---
title: "NIH_funds_FY1999"
author: "Nick_Fox"
date: "February 10, 2016"
output: html_document
---

The goal of this rmd file is to develop code to quickly accumulate the relevant information from the NIH's RePORTER files for analyzing R01 funding data.

```{r echo = FALSE}
#install.packages("dplyr")
#install.packages("ggplot2")
#install.packages("tidyr")
#install.packages("data.table")



library(dplyr)
library(tidyr)
library(ggplot2)
library(data.table)
#loads in all packages used in this analysis.  Find install code above.


Sem <- function(x) {
  sqrt(var(x)/length(x))
  }
#creates function to calculate the standard error of the mean, SEM




summarySE <- function(data=NULL, measurevar, groupvars=NULL, na.rm=FALSE,
                      conf.interval=.95, .drop=TRUE) {
    library(plyr)

    # New version of length which can handle NA's: if na.rm==T, don't count them
    length2 <- function (x, na.rm=FALSE) {
        if (na.rm) sum(!is.na(x))
        else       length(x)
    }

    # This does the summary. For each group's data frame, return a vector with
    # N, mean, and sd
    datac <- ddply(data, groupvars, .drop=.drop,
      .fun = function(xx, col) {
        c(N    = length2(xx[[col]], na.rm=na.rm),
          mean = mean   (xx[[col]], na.rm=na.rm),
          sd   = sd     (xx[[col]], na.rm=na.rm)
        )
      },
      measurevar
    )

    # Rename the "mean" column    
    datac <- rename(datac, c("mean" = measurevar))

    datac$se <- datac$sd / sqrt(datac$N)  # Calculate standard error of the mean

    # Confidence interval multiplier for standard error
    # Calculate t-statistic for confidence interval: 
    # e.g., if conf.interval is .95, use .975 (above/below), and use df=N-1
    ciMult <- qt(conf.interval/2 + .5, datac$N-1)
    datac$ci <- datac$se * ciMult

    return(datac)
}


normDataWithin <- function(data=NULL, idvar, measurevar, betweenvars=NULL,
                           na.rm=FALSE, .drop=TRUE) {
    library(plyr)

    # Measure var on left, idvar + between vars on right of formula.
    data.subjMean <- ddply(data, c(idvar, betweenvars), .drop=.drop,
     .fun = function(xx, col, na.rm) {
        c(subjMean = mean(xx[,col], na.rm=na.rm))
      },
      measurevar,
      na.rm
    )

    # Put the subject means with original data
    data <- merge(data, data.subjMean)

    # Get the normalized data in a new column
    measureNormedVar <- paste(measurevar, "_norm", sep="")
    data[,measureNormedVar] <- data[,measurevar] - data[,"subjMean"] +
                               mean(data[,measurevar], na.rm=na.rm)

    # Remove this subject mean column
    data$subjMean <- NULL

    return(data)
}


summarySEwithin <- function(data=NULL, measurevar, betweenvars=NULL, withinvars=NULL,
                            idvar=NULL, na.rm=FALSE, conf.interval=.95, .drop=TRUE) {

  # Ensure that the betweenvars and withinvars are factors
  factorvars <- vapply(data[, c(betweenvars, withinvars), drop=FALSE],
    FUN=is.factor, FUN.VALUE=logical(1))

  if (!all(factorvars)) {
    nonfactorvars <- names(factorvars)[!factorvars]
    message("Automatically converting the following non-factors to factors: ",
            paste(nonfactorvars, collapse = ", "))
    data[nonfactorvars] <- lapply(data[nonfactorvars], factor)
  }

  # Get the means from the un-normed data
  datac <- summarySE(data, measurevar, groupvars=c(betweenvars, withinvars),
                     na.rm=na.rm, conf.interval=conf.interval, .drop=.drop)

  # Drop all the unused columns (these will be calculated with normed data)
  datac$sd <- NULL
  datac$se <- NULL
  datac$ci <- NULL

  # Norm each subject's data
  ndata <- normDataWithin(data, idvar, measurevar, betweenvars, na.rm, .drop=.drop)

  # This is the name of the new column
  measurevar_n <- paste(measurevar, "_norm", sep="")

  # Collapse the normed data - now we can treat between and within vars the same
  ndatac <- summarySE(ndata, measurevar_n, groupvars=c(betweenvars, withinvars),
                      na.rm=na.rm, conf.interval=conf.interval, .drop=.drop)

  # Apply correction from Morey (2008) to the standard error and confidence interval
  #  Get the product of the number of conditions of within-S variables
  nWithinGroups    <- prod(vapply(ndatac[,withinvars, drop=FALSE], FUN=nlevels,
                           FUN.VALUE=numeric(1)))
  correctionFactor <- sqrt( nWithinGroups / (nWithinGroups-1) )

  # Apply the correction factor
  ndatac$sd <- ndatac$sd * correctionFactor
  ndatac$se <- ndatac$se * correctionFactor
  ndatac$ci <- ndatac$ci * correctionFactor

  # Combine the un-normed means with the normed results
  merge(datac, ndatac)
}

asNumeric <- function(x) as.numeric(as.character(x))
factorsNumeric <- function(d) modifyList(d, lapply(d[, sapply(d, is.factor)],   
                                                   asNumeric))
#functions that allow easy conversions of factors to numeric

#FOR MAC, use the WD below:
setwd("~/Dropbox/GitHub_master/data/NIH_awards")

```

```{r echo = FALSE}

a <- read.csv("RePORTER_PRJ_C_FY1999.csv", header = TRUE, stringsAsFactors = FALSE)
#load in all NIH award data for the fiscal year of choice (in file name - FYXXXX)

b <- a %>% 
  filter(ACTIVITY == "R01")
#makes a new dataframe with just R01 award data

b <- b %>% 
  separate(col = PI_IDS, into = c("PI_1", "PI_2", "PI_3", "PI_4", "PI_5", "PI_6", "PI_7", "PI_8", "PI_9", "PI_10", "PI_11"), sep = "\\;")
#makes a new column for each PI on an R01

b[b == ""] <- NA
#[is.na(b)] <- 0
#replaces blank cells with NA (could further turn NAs into zeroes with the second line)

b <- as.data.frame(sapply(b, gsub, pattern = "contact", replacement = ""), stringsAsFactors = FALSE)
#removes "contact" information from the PI columns

b$TOTAL_COST <- as.numeric(as.character(b$TOTAL_COST))
#converts TOTAL_COST from factor to numeric

#b <- b %>%
#  filter(!is.na(TOTAL_COST)) %>% 
#  mutate(SUM_COST = sum(TOTAL_COST))
#computes the total amount dispersed in R01s in that fiscal year and makes a new column: SUM_COST

b <- b %>% 
  mutate(PI_1_DUMMY = ifelse(!is.na(PI_1), 1, 0), PI_2_DUMMY = ifelse(!is.na(PI_2), 1, 0), PI_3_DUMMY = ifelse(!is.na(PI_3), 1, 0), PI_4_DUMMY = ifelse(!is.na(PI_4), 1, 0), PI_5_DUMMY = ifelse(!is.na(PI_5), 1, 0), PI_6_DUMMY = ifelse(!is.na(PI_6), 1, 0), PI_7_DUMMY = ifelse(!is.na(PI_7), 1, 0), PI_8_DUMMY = ifelse(!is.na(PI_8), 1, 0), PI_9_DUMMY = ifelse(!is.na(PI_9), 1, 0), PI_10_DUMMY = ifelse(!is.na(PI_10), 1, 0), PI_11_DUMMY = ifelse(!is.na(PI_11), 1, 0), TOTAL_PIS = PI_1_DUMMY + PI_2_DUMMY + PI_3_DUMMY + PI_4_DUMMY + PI_5_DUMMY + PI_6_DUMMY + PI_7_DUMMY + PI_8_DUMMY + PI_9_DUMMY + PI_10_DUMMY + PI_11_DUMMY)
#this big mess dummy codes each PI position on the R01, and then adds them all up to get a total number of PIs per grant

```

```{r echo = FALSE}
#b %>% 
#  ggplot(aes(x = TOTAL_PIS, y = TOTAL_COST)) + geom_point(position = "jitter", alpha = 0.4, size = 2.5) + stat_smooth(method = "lm", size = 2, alpha = 0.4) + ggtitle("Value of R01 funding per PI author") + theme_bw() + theme(axis.line = element_line(colour = "black"), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.border = element_blank(), panel.background = element_blank())
#makes figure displaying the amount of a grant (TOTAL_COST) against the number of PIs on that R01

#lm_PI_COST <- lm(TOTAL_COST ~ TOTAL_PIS + ORG_DEPT + ORG_STATE + ED_INST_TYPE, data = b)
#summary(lm_PI_COST)
#linear regression model for TOTAL_COST regressed on TOTAL_PIS controlling for department type, state, and institution type.
```

```{r echo = FALSE}

b <- b %>% 
  group_by(PI_1) %>% 
  mutate(MONEY_PER_PI = sum(TOTAL_COST))
#calculates R01 money dispersed to each PI

b <- b %>% 
  group_by(PI_1, ACTIVITY) %>% 
  mutate(NUMBER_OF_R01s = n())
#counts number of R01s going to each PI

c <- b %>% 
  group_by(NUMBER_OF_R01s) %>% 
  mutate(COST_NUMBER_OF_R01s = sum(TOTAL_COST)) %>% 
  distinct(NUMBER_OF_R01s) %>% 
  select(NUMBER_OF_R01s, COST_NUMBER_OF_R01s) %>% 
  arrange(NUMBER_OF_R01s)
#calculates how much money goes to PIs with that number of grants
#example - ~2.6 billion dollars went to PIs who received funding from 2 R01s in FY2013
#this is also the best way to glean this data - just view data frame c.

table(b$NUMBER_OF_R01s)
#prints table of frequencies for each number of grants (how many PIs have how many grants)

table(b$ACTIVITY)
#prints total number of R01s funded in given fiscal year

table(b$SUM_COST)
#total amount of money dispersed through R01s in given fiscal year

print(c)
#prints the data frame with COST_NUMBER_OF_R01
```

Some figures:
```{r echo = FALSE}
# b %>% 
#   ggplot(aes(x = ORG_DEPT, y = TOTAL_COST)) + geom_bar(stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1))
# 
# b %>% 
#   ggplot(aes(x = ORG_DEPT, y = TOTAL_COST)) + geom_point() + theme(axis.text.x = element_text(angle = 45, hjust = 1))
# 
# b_all_dup %>% 
#   ggplot(aes(x = ORG_DEPT, y = DUP_COST)) + geom_bar(stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1))

```
